#!/usr/bin/env node

const program = require('commander');
const path = require('path');
const {execSync} = require('child_process');

function execute() {
  const {testPath} = require(program.config);
  return execSync(`RNSST_CONFIG_PATH="${program.config}" detox test ${program.detoxArgs} ${testPath}`, {stdio: 'inherit'});
}

program
  .version('0.0.1')
  .option('-c, --config <path>', 'custom path to config. Defaults to ./rnsst-config.js', path.resolve(process.cwd(), './rnsst-config.js'))
  .option('-d, --detox-args <args>', 'arguments to pass to detox', '');

program
  .command('test')
  .description('Compare your stories to reference screenshots')
  .action(() => {
    execute();
  });

program
  .on('--help', () => {
    console.log('');
    console.log('To set-up first create "./rnsst-config.js" file. File contents:');
    console.log(`
const path = require('path');
module.exports = {
  testPath: path.resolve(__dirname, './e2e/storybook.spec.js'), //path where your spec file exists 
  port: 6006, // Optional port to run storybook server on, default is 7007
  applitools: {
  apiKey: 'EYES_API_KEY', //Your key from applitools,
    appName: 'Your app Name',
    serverUrl: 'applitools server url', //Optional, leave empty if not using custom server
    batchId: 'Unique batch number, can simply be uuid.v4()',
  }
};
`);
    console.log('Then create "storybook.spec.js" file in your detox tests. File contents: \n');
    console.log("require('rnsst')(async () => {}...optional function to call before running screenshot tests)");
  });


program.parse(process.argv);
